### ISSUE TITLE
ionic onIonTabsDidChange will be ignored

### ISSUE THREAD

**Issue by peterpeterparker** [peterpeterparker/tietracker#96]
👉 Ionic issue https://github.com/ionic-team/ionic-framework/issues/21827

Warning: Unknown event handler property `onIonTabsDidChange`. It will be ignored.
    at div
    at PageManager (http://localhost:3000/static/js/vendors~main.chunk.js:19971:5)
    at IonTabs (http://localhost:3000/static/js/vendors~main.chunk.js:20467:5)
    at NavManager (http://localhost:3000/static/js/vendors~main.chunk.js:21115:5)
    at IonRouterInner (http://localhost:3000/static/js/vendors~main.chunk.js:17747:5)
    at IonRouter (http://localhost:3000/static/js/vendors~main.chunk.js:123346:37)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:122724:30)
    at IonReactRouter (http://localhost:3000/static/js/vendors~main.chunk.js:18016:5)
    at ion-app
    at ReactComponent (http://localhost:3000/static/js/vendors~main.chunk.js:19575:7)
    at IonApp
    at Suspense
    at App (http://localhost:3000/static/js/main.chunk.js:1401:95)
    at Connect(App) (http://localhost:3000/static/js/vendors~main.chunk.js:119974:75)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:119687:20)

**Comment by peterpeterparker** [comment]
Resolved by Ionic
